### ISSUE TITLE
Uncaught exception on Open File

### ISSUE THREAD

**Issue by ethamitc** [SkyHawkB/Hawk#2]
If you open the open file dialogue and then hit cancel it does this:

![image](https://user-images.githubusercontent.com/27776796/45589314-86067780-b8f1-11e8-9d2c-da8f802add64.png)

**Comment by SkyHawkB** [comment]
This has been fixed by [f26c52](https://github.com/SkyHawkB/Hawk/commit/f26c5272f543e1f077a258cfdd0c41f8655af498), which will take effect in the next version.
