### ISSUE TITLE
[Feature] Different Font

### ISSUE THREAD

**Issue by ethamitc** [SkyHawkB/Hawk#3]
Maybe consider changing the font? it doesn't quite fit in in my opinion.

**Comment by SkyHawkB** [comment]
I will make this an option once I have added settings.

**Comment by SkyHawkB** [comment]
Added in [4e9c1b](https://github.com/SkyHawkB/Hawk/commit/4e9c1b94b2a35cf06a8b2eba521ee79422ee3496).
