### ISSUE TITLE
UI completely breaks when run using source code.

### ISSUE THREAD

**Issue by ethamitc** [SkyHawkB/Hawk#7]
I ran Hawk using the source code and the command `npm start`, and the UI was completely broken. Any idea why?

**Comment by kierajreed** [comment]
Can you provide more details? Steps to reproduce? Screenshots?

**Comment by ethamitc** [comment]
**Them Extra Juicy Details**
I downloaded the source code with git clone, then I ran your test command `npm start` and when the electron app opened the UI was super fucced.

**Steps to reproduce**
1. Download source code using `git clone https://github.com/skyhawkb/hawk.git`
2. Open the folder in git bash and run the console command `npm start`.
3. Watch the UI get fucked.

**Comment by kierajreed** [comment]
I have found the issue. There is no CSS file to add the UI styles.

To fix this, do `npm run compile-less` and try running it again.
